server:
  port: 8888

spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloudframeworks-springcloud/Spring-Cloud-Config.git
          searchPaths: config